version: "3"
services:
  redis:
    container_name: trophy-redis
    image: redis:latest
    ports:
      - "6379:6379"
  deno-app:
    container_name: trophy-web
    build: .
    volumes:
      - .:/app
    ports:
      - "8890:8080"
    environment:
      - DENO_ENV=development
    command: ["deno", "run", "--watch", "-A", "main.ts"]
